account:
	openapi-generator generate \
		-i=./accounts/specs/accounts.json \
		--api-package=CanvasAccountKit \
		--config=/Users/stevenprichard/Developer/GaTech/edtech/swagger/accounts/gen-config.json \
		-g=swift5 \
		-o=/Users/stevenprichard/Developer/GaTech/edtech/swagger/accounts/CanvasAccountKit
