name: CanvasAccountKit
targets:
  CanvasAccountKit:
    type: framework
    platform: iOS
    deploymentTarget: "10.0"
    sources: [CanvasAccountKit]
    info:
      path: ./Info.plist
      version: 1.0
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    
